

services:
  app:
    build: 
      context: ../
      dockerfile: Dockerfile
      target: devcontainer
    volumes:
      - ../:/var/workspace
      - ~/.ssh:/root/.ssh:ro
    env_file:
      - .env
    ports:
      - 8080:8080
    
  

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    volumes:
      - mysql_volume:/var/lib/mysql

volumes:
  mysql_volume:
